version: '2.3'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elastic_warehouse
    environment:
      - cluster.name=data_warehouse
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    volumes:
      - elastic-warehouse-volume:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
  elastic-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elastic_warehouse_test
    environment:
      - cluster.name=data_warehouse_test
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    volumes:
      - elastic-warehouse-test-volume:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9201:9200"
      - "9301:9300"
volumes:
  elastic-warehouse-volume:
    driver: local
  elastic-warehouse-test-volume:
    driver: local
